fixtures:
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "mongodb": "git://github.com/puppetlabs/puppetlabs-mongodb.git"
    "nodejs": "git://github.com/puppetlabs/puppetlabs-nodejs.git"
    "ruby": "git://github.com/puppetlabs/puppetlabs-ruby.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "sudo": "git://github.com/saz/puppet-sudo.git"
    "tftp": "git://github.com/puppetlabs/puppetlabs-tftp.git"
    "vcsrepo": "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    "xinetd": "git://github.com/puppetlabs/puppetlabs-xinetd.git"
  symlinks:
    "razor": "#{source_dir}"
