name    'puppetlabs-razor'
version '0.2.1'
source  'git@github.com:puppetlabs/puppetlabs-razor.git'
author  'Puppet Labs'
license 'Apache 2.0'
summary 'Razor puppet module'
description 'Razor provisioning system puppet installation module'
project_page 'https://github.com/puppetlabs/puppetlabs-razor'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 2.0.0'
dependency 'puppetlabs/mongodb', '>= 0.1.0'
dependency 'puppetlabs/nodejs', '>= 0.1.1'
dependency 'puppetlabs/ruby', '>= 0.0.2'
dependency 'puppetlabs/tftp', '>= 0.2.0'
dependency 'puppetlabs/vcsrepo', '>= 0.0.4'
dependency 'saz/sudo', '>= 2.0.0'
